name: Sync upstream

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        UPSTREAM: ['openwrt']
        VERSION: ['23.05', '24.10', 'master']

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          path: workdir
          fetch-depth: 0

      - name: Checkout upstream (openwrt)
        uses: actions/checkout@v5
        if: matrix.UPSTREAM == 'openwrt'
        with:
          path: upstream
          repository: openwrt/packages
          ref: ${{ matrix.VERSION != 'master' && 'openwrt-' || '' + matrix.VERSION }}
          fetch-depth: 1

      - name: Confugure git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'noreply@github.com'

      - name: Prepare branch
        run: |
          cd workdir
          git switch --orphan ${{ matrix.UPSTREAM }}-${{ matrix.VERSION }} || git switch ${{ matrix.UPSTREAM }}-${{ matrix.VERSION }}
          rm -rf ./*
      
      - name: Sync files
        run: |
          cd workdir
          cp -r ../upstream/lang/golang/* ./

      - name: Commit and push changes
        run: |
          cd workdir
          git add .
          git commit -m "Sync from ${{ matrix.UPSTREAM }}/packages:${{ matrix.VERSION }}" || echo "No changes to commit"
          git push origin ${{ matrix.UPSTREAM }}-${{ matrix.VERSION }} --force
