name: Sync upstream

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        VERSION: ['23.05', '24.10']

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          path: workdir
          fetch-depth: 0

      - name: Checkout upstream
        uses: actions/checkout@v5
        with:
          path: upstream
          repository: openwrt/packages
          ref: openwrt-${{ matrix.VERSION }}
          fetch-depth: 1

      - name: Confugure git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'noreply@github.com'

      - name: Prepare branch
        run: |
          cd workdir
          git switch --orphan ${{ matrix.VERSION }} || git switch ${{ matrix.VERSION }}
          rm -rf ./*
      
      - name: Sync files
        run: |
          cd workdir
          cp -r ../upstream/lang/golang/* ./

      - name: Commit and push changes
        run: |
          cd workdir
          git add .
          git commit -m "Sync from openwrt/packages:${{ matrix.VERSION }}" || echo "No changes to commit"
          git push origin ${{ matrix.VERSION }} --force
